language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - ILLUMINATE_VERSION=5.5.*
  - ILLUMINATE_VERSION=5.7.*
  - ILLUMINATE_VERSION=5.6.*
  - ILLUMINATE_VERSION=5.8.*
  - ILLUMINATE_VERSION=^6.0

matrix:    # Laravel 6.0 does not support PHP 7.1
  exclude:
    - php: 7.1
      env: ILLUMINATE_VERSION=^6.0

before_install:
  - composer require illuminate/support:${ILLUMINATE_VERSION} illuminate/http:${ILLUMINATE_VERSION} --no-update

install:
  - composer install --no-interaction --no-progress --no-suggest --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover --verbose

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
